# Configuration file for SMSAlertForge

# Configuration for message generation
messages:
  num_messages: 1000  # Number of messages to generate

# Configuration for message senders
senders:
  num_senders: 3         # Number of sender threads
  failure_rate: 0.3       # Failure rate for message sending (e.g., 0.1 for 10% failure)
  mean_processing_time: 0.01  # Mean processing time for each message in seconds

# Configuration for progress monitor
progress_monitor:
  update_interval: 0.01  # Update interval for progress monitor in seconds

# Logging configuration
logging:
  level: INFO  # Logging level (e.g., DEBUG, INFO, WARNING, ERROR, CRITICAL)
  to_console: false  # Set to false if you don't want logs on the console
  to_file: true  # Set to false if you don't want logs in a file